import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { TailwindCssNotification } from "../components/utility-first/tailwind-css-notification";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1 className="title">
					Read{" "}
					<Link href="/about">
						<a>about page!</a>
					</Link>
				</h1>
			</main>
			<TailwindCssNotification />
		</>
	);
};

export default Home;
